---
- name: Create directory for vector "{{ vector_dir }}"
  become: true
  ansible.builtin.file:
    path: "{{ vector_dir }}"
    mode: "0644"
    state: directory

- name: Create directory for vector "/etc/vector"
  become: true
  ansible.builtin.file:
    path: "/etc/vector"
    mode: "0644"
    state: directory

- name: Create directory for vector "/var/lib/vector"
  become: true
  ansible.builtin.file:
    path: "/var/lib/vector"
    mode: "0644"
    state: directory

- name: Create directory for vector "/run/systemd/system"
  become: true
  ansible.builtin.file:
    path: "/run/systemd/system"
    mode: "0644"
    state: directory

- name: Get vector distrib
  become: true
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    mode: "0644"

- name: Extract vector in the installation directory
  become: true
  ansible.builtin.unarchive:
    copy: false
    src: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "{{ vector_dir }}"
    extra_opts: ['--strip-components=2']

- name: Remove vector packages distribs
  become: true
  ansible.builtin.file:
    path: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    state: file

- name: Copy server configuration file
  become: true
  ansible.builtin.copy:
    content: "{{vector_config}}"
    dest: "{{ vector_dir }}/vector.yaml"
    mode: "0644"

- name: Copy server configuration file
  become: true
  ansible.builtin.template:
    src: vector.toml.j2
    dest: /etc/vector/vector.toml
    mode: "0644"

- name: Create a symbolic link to vector
  ansible.builtin.file:
    src: "{{ vector_dir }}/bin/vector"
    dest: "/usr/bin/vector"
    state: link
