---
- name: Create directory for vector "{{ vector_dir }}"
  become: true
  ansible.builtin.file:
    path: "{{ vector_dir }}"
    mode: "0755"
    state: directory

- name: Get vector distrib
  become: true
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    mode: "0755"

- name: Extract vector in the installation directory
  become: true
  ansible.builtin.unarchive:
    copy: false
    src: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "{{ vector_dir }}"
    extra_opts: ['--strip-components=2']

- name: Remove vector packages distribs
  become: true
  ansible.builtin.file:
    path: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    state: file

- name: Copy server configuration file
  become: true
  ansible.builtin.copy:
    content: "{{vector_config}}"
    dest: "{{ vector_dir }}/vector.yaml"
    mode: "0644"
