---
clickhouse:
  hosts:
    study-0:
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/yc
      ansible_host: 158.160.114.253

vector:
  hosts:
    study-1:
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/yc
      ansible_host: 158.160.119.92

lighthouse:
  hosts:
    study-2:
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/yc
      ansible_host: 158.160.108.205