pipeline {
    agent {
        label 'ansible'
    }
    stages{
        stage('Git repo') {
            steps {
                git branch: 'main', url: 'https://github.com/AVasMakarov/devops-netology.git'
            }
        }
        stage('test') {
            steps {
                dir('./Homework/8/5/playbook/roles/vector-role') {
                sh 'molecule test'
                }
            }
        }

        stage('Remove') {
            steps {
                deleteDir()

            }
        }
    }
}